# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(blank=True, max_length=2, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('is_variation', models.BooleanField(default=False)),
                ('code', models.IntegerField()),
                ('family', models.IntegerField(default=1)),
                ('is_complement', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcas.Brands', verbose_name='Marcas')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
