# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20180219_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visibility', models.BooleanField(default=True)),
                ('price', models.IntegerField(blank=True)),
                ('price_offer', models.IntegerField(blank=True)),
                ('offer_day_form', models.DateTimeField(auto_now=True)),
                ('offer_day_to', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(blank=True)),
                ('sku', models.IntegerField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productos.Product', verbose_name='Productos')),
            ],
        ),
    ]
