# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_productdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='price_offer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
