# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20180220_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='productos.Product', verbose_name='Productos'),
        ),
    ]
